 -- 코드를 입력하세요
SELECT NAME, COUNT(NAME)
  FROM ANIMAL_INS
  WHERE NAME IS NOT NULL
 GROUP BY NAME
HAVING COUNT(NAME) > 1
 ORDER BY NAME ASC




 -- 입원 시각 구하기

SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR, COUNT(*)
  FROM ANIMAL_OUTS
 WHERE DATE_FORMAT(DATETIME, '%H') >= 09
   AND DATE_FORMAT(DATETIME, '%H') <= 19
 GROUP BY HOUR
 ORDER BY HOUR ASC;



-- 입양 시각 구하기(2)

 WITH RECURSIVE num(HOUR) AS (
    SELECT 0
    UNION ALL 
    SELECT HOUR+1 FROM num WHERE HOUR<23
)

SELECT A.HOUR, 
       CASE WHEN B.CNT IS NULL 
            THEN 0 
            ELSE B.CNT END AS COUNT 
  FROM num A
  LEFT JOIN (SELECT HOUR(DATETIME) AS H, 
                    COUNT (ANIMAL_ID) AS CNT
               FROM ANIMAL_OUTS 
              GROUP BY 1) AS B 
    ON A.HOUR = B.H