-- 이름이 없는 동물의 아이디
SELECT ANIMAL_ID
  FROM ANIMAL_INS
 WHERE NAME IS NULL;

 -- 이름이 있는 동물의 아이디 
SELECT ANIMAL_ID
  FROM ANIMAL_INS
 WHERE NAME IS NOT NULL
 ORDER BY ANIMAL_ID ASC

-- 코드를 입력하세요
SELECT ANIMAL_TYPE, IFNULL(NAME, 'NO NAME'), SEX_UPON_INTAKE
  FROM ANIMAL_INS
 ORDER BY ANIMAL_ID ASC