-- 없어진 기록찾기 
SELECT AO.ANIMAL_ID, AO.NAME
  FROM ANIMAL_OUTS AS AO
  LEFT OUTER JOIN ANIMAL_INS AS AI
    ON AI.ANIMAL_ID = AO.ANIMAL_ID
 WHERE AI.ANIMAL_ID IS NULL

-- 있었는데요 없었습니다
SELECT AI.ANIMAL_ID, AI.NAME
  FROM ANIMAL_INS AS AI 
  JOIN ANIMAL_OUTS AS AO
    ON AI.ANIMAL_ID = AO.ANIMAL_ID
 WHERE AI.DATETIME >= AO.DATETIME
 ORDER BY AI.DATETIME


-- 오랜 기간 보호한 동물(1)
SELECT AI.NAME, AI.DATETIME
  FROM ANIMAL_INS AS AI 
  LEFT OUTER JOIN ANIMAL_OUTS AS AO
    ON AI.ANIMAL_ID = AO.ANIMAL_ID
 WHERE AO.ANIMAL_ID IS NULL
 ORDER BY AI.DATETIME ASC 
 LIMIT 3

-- 보호소에서 중성화한 동물

 SELECT AO.ANIMAL_ID, AO.ANIMAL_TYPE, AI.NAME
  FROM ANIMAL_OUTS AS AO
  JOIN ANIMAL_INS AS AI
    ON AI.ANIMAL_ID = AO.ANIMAL_ID
 WHERE AI.SEX_UPON_INTAKE != AO.SEX_UPON_OUTCOME
   AND AI.SEX_UPON_INTAKE IN ('Intact Male', 'Intact Female')
 ORDER BY AO.ANIMAL_ID ASC